{
    "name": "B-good: B-BBEE Procurement Control",
    "summary": "Track supplier B-BBEE evidence, procurement spend, and recognised spend.",
    "version": "18.0.1.0.0",
    "category": "Accounting/Accounting",
    "author": "B-good",
    "license": "LGPL-3",
    "depends": [
        "account",
        "base",
        "mail",
        "purchase",
    ],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/default_rule_sets.xml",
        "data/scheduled_actions.xml",
        "data/mail_templates.xml",
        "views/supplier_profile_views.xml",
        "views/supplier_certificate_views.xml",
        "views/spend_batch_views.xml",
        "views/spend_line_views.xml",
        "views/scorecard_assessment_views.xml",
        "views/evidence_pack_views.xml",
        "views/dashboard_views.xml",
        "views/purchase_order_views.xml",
        "views/menu_views.xml",
        "reports/evidence_pack_report.xml",
        "reports/missing_evidence_report.xml",
        "reports/spend_schedule_report.xml",
    ],
    "application": True,
    "installable": True,
}
